### ISSUE TITLE
new props for renderers: loadingRenderer and innerRenderer (for groups)

### ISSUE THREAD

**Issue by gabrielenosso** [ceolter/ag-grid-react-component#1]
Could it be possible to add a options like loadingRenderer and innerRenderer that would work like cellRenderer but respectively for the loading template and group row?
(using the reactCellRendererFactory() method or similar)

**Comment by ceolter** [comment]
did you put this into the wrong project? shouldn't it be part of ag-grid and not ag-grid-react-component?

**Comment by gabrielenosso** [comment]
Yeah, you're right. I'll close this one and open a new one there.
Sorry! :)
